import torch
from typing import Union, List, Optional
from tqdm import tqdm
from .base_inverse import BaseInverseSampler
from ...core.base_operator import BaseOperator, MaskingOperator

class RepaintSampler(BaseInverseSampler):
    """Hard Replacement (Repaint) methodology for Inpainting models.
    
    Implements the RePaint algorithm (Lugmayr et al., 2022) which alternates between
    reverse diffusion steps and forward "jump-back" re-noising to harmonize the
    known and unknown regions. Known regions are replaced with noised observations
    at each step, while unknown regions are generated by the model.
    
    Key: during jump-back, known and unknown regions are re-noised independently
    to prevent information leakage from corrupting the known-region signal.
    """

    def __init__(
        self, 
        method, model, device, steps=50, feature_keys=None,
        operator: Optional[BaseOperator] = None,
        y: Optional[torch.Tensor] = None,
        init_x: Optional[torch.Tensor] = None,
        start_ratio: float = 1.0,
        jump_n_sample: int = 10
    ):
        super().__init__(method, model, device, steps, feature_keys, init_x, start_ratio)
        self.operator = operator
        self.y = y
        self.jump_n_sample = jump_n_sample
        
        if self.operator is not None:
             self.operator.to(self.device)
        if self.y is not None:
             self.y = self.y.to(self.device)
             
        if self.operator is not None and not isinstance(self.operator, MaskingOperator):
            raise ValueError("Repaint requires a MaskingOperator to define known regions explicitly.")

    def _sample_batch(self, current_batch_size: int, shape: Union[torch.Size, List[int]], condition: Optional[torch.Tensor] = None) -> torch.Tensor:
        x_t, time_seq = self._initialize_state(current_batch_size, shape)
        
        y_cond = self.y
        if y_cond is not None and y_cond.shape[0] == 1 and current_batch_size > 1:
            y_cond = y_cond.repeat(current_batch_size, *[1]*(y_cond.ndim - 1))
        
        mask = self.operator.mask if self.operator is not None else None
            
        for i, t_idx in enumerate(tqdm(time_seq, desc="Repaint Steps", leave=False)):
            prev_t_idx = t_idx - (self.method.timesteps // self.steps)
            if prev_t_idx < 0: prev_t_idx = -1 
            
            alpha_bar_t = self._get_alpha_bar(t_idx, len(shape))
            alpha_bar_prev = self._get_alpha_bar(prev_t_idx, len(shape))
            t_float = t_idx / self.method.timesteps
            
            for rep in range(self.jump_n_sample):
                with torch.no_grad():
                    pred_noise = self.method.predict(self.model, x_t, t_float, condition)
                    pred_x0 = (x_t - torch.sqrt(1 - alpha_bar_t) * pred_noise) / torch.sqrt(alpha_bar_t)
                    
                    if prev_t_idx >= 0:
                        # DDPM reverse step with stochastic noise
                        sigma_t = torch.sqrt((1 - alpha_bar_prev) / (1 - alpha_bar_t) * (1 - alpha_bar_t / alpha_bar_prev))
                        dir_xt = torch.sqrt(1 - alpha_bar_prev - sigma_t**2) * pred_noise
                        noise = torch.randn_like(x_t)
                        x_prev = torch.sqrt(alpha_bar_prev) * pred_x0 + dir_xt + sigma_t * noise
                    else:
                        # Final step: deterministic
                        x_prev = pred_x0
    
                    # Hard replacement: composite known region from observation
                    if mask is not None and y_cond is not None:
                        if prev_t_idx >= 0:
                            # Re-noise the clean observation to match the noise level at t-1
                            true_noise = torch.randn_like(y_cond)
                            y_noisy = torch.sqrt(alpha_bar_prev) * y_cond + torch.sqrt(1 - alpha_bar_prev) * true_noise
                            x_prev = mask * y_noisy + (1 - mask) * x_prev
                        else:
                            # Final step: use clean observation directly
                            x_prev = mask * y_cond + (1 - mask) * x_prev
                            
                if rep < self.jump_n_sample - 1 and prev_t_idx >= 0:
                    # Jump back: re-noise known and unknown regions INDEPENDENTLY
                    # Unknown region: forward diffuse from the denoised x_prev
                    noise_unknown = torch.randn_like(x_prev)
                    x_t_unknown = torch.sqrt(alpha_bar_t) * x_prev + torch.sqrt(1 - alpha_bar_t) * noise_unknown
                    
                    if mask is not None and y_cond is not None:
                        # Known region: forward diffuse from the CLEAN observation y
                        noise_known = torch.randn_like(y_cond)
                        x_t_known = torch.sqrt(alpha_bar_t) * y_cond + torch.sqrt(1 - alpha_bar_t) * noise_known
                        # Composite
                        x_t = mask * x_t_known + (1 - mask) * x_t_unknown
                    else:
                        x_t = x_t_unknown
                else:
                    x_t = x_prev

        return x_t
